version: '3.8'

services:
  ferricstore-1:
    build: .
    environment:
      FERRICSTORE_PORT: "6379"
      FERRICSTORE_NODE_NAME: "ferricstore@ferricstore-1"
      FERRICSTORE_COOKIE: "benchmark"
      FERRICSTORE_CLUSTER_NODES: "ferricstore@ferricstore-2,ferricstore@ferricstore-3"
    volumes:
      - data1:/data
    networks:
      - bench

  ferricstore-2:
    build: .
    environment:
      FERRICSTORE_PORT: "6379"
      FERRICSTORE_NODE_NAME: "ferricstore@ferricstore-2"
      FERRICSTORE_COOKIE: "benchmark"
      FERRICSTORE_CLUSTER_NODES: "ferricstore@ferricstore-1,ferricstore@ferricstore-3"
    volumes:
      - data2:/data
    networks:
      - bench

  ferricstore-3:
    build: .
    environment:
      FERRICSTORE_PORT: "6379"
      FERRICSTORE_NODE_NAME: "ferricstore@ferricstore-3"
      FERRICSTORE_COOKIE: "benchmark"
      FERRICSTORE_CLUSTER_NODES: "ferricstore@ferricstore-1,ferricstore@ferricstore-2"
    volumes:
      - data3:/data
    networks:
      - bench

  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./bench/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - ferricstore-1
      - ferricstore-2
      - ferricstore-3
    networks:
      - bench

volumes:
  data1:
  data2:
  data3:

networks:
  bench:
    driver: bridge
