defmodule Ferricstore.AclPersistenceTest do
  @moduledoc """
  Tests for ACL file persistence: SAVE, LOAD, auto-load on startup,
  auto-save on mutations, and comprehensive edge cases.

  These tests use temporary directories to avoid interfering with the
  real data directory. Each test gets a fresh directory and a clean ACL
  state via Acl.reset!/0.
  """

  use ExUnit.Case, async: false

  alias Ferricstore.Acl

  setup do
    Acl.reset!()
    tmp_dir = Path.join(System.tmp_dir!(), "acl_test_#{System.unique_integer([:positive])}")
    File.mkdir_p!(tmp_dir)

    on_exit(fn ->
      Acl.reset!()
      File.rm_rf!(tmp_dir)
    end)

    %{tmp_dir: tmp_dir}
  end

  # Helper to extract key glob strings from compiled patterns
  defp key_globs(patterns) when is_list(patterns) do
    Enum.map(patterns, fn {glob, _mode, _regex} -> glob end)
  end

  defp key_globs(:all), do: :all

  # ---------------------------------------------------------------------------
  # ACL SAVE -- basic functionality
  # ---------------------------------------------------------------------------

  describe "save/1 basic" do
    test "saves default-only ACL to file", %{tmp_dir: dir} do
      assert :ok = Acl.save(dir)
      path = Acl.acl_file_path(dir)
      assert File.exists?(path)
    end

    test "saved file contains header comment", %{tmp_dir: dir} do
      assert :ok = Acl.save(dir)
      contents = File.read!(Acl.acl_file_path(dir))
      assert contents =~ "# FerricStore ACL configuration"
      assert contents =~ "# Generated by ACL SAVE at"
    end

    test "saved file contains default user line", %{tmp_dir: dir} do
      assert :ok = Acl.save(dir)
      contents = File.read!(Acl.acl_file_path(dir))
      assert contents =~ "user default on nopass ~* &* +@all"
    end

    test "saved file has 0600 permissions", %{tmp_dir: dir} do
      assert :ok = Acl.save(dir)
      {:ok, stat} = File.stat(Acl.acl_file_path(dir))
      # 0600 = 384 in decimal, but File.stat returns the full mode including
      # file type bits. We check the permission bits only.
      assert Bitwise.band(stat.mode, 0o777) == 0o600
    end

    test "saves multiple users", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", ">s3cret", "~cache:*", "-@all", "+get", "+set"])
      assert :ok = Acl.set_user("bob", ["off"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      assert contents =~ "user alice"
      assert contents =~ "user bob"
      assert contents =~ "user default"
    end

    test "users are sorted alphabetically in file", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("zara", ["on"])
      assert :ok = Acl.set_user("alice", ["on"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))

      lines =
        contents
        |> String.split("\n")
        |> Enum.filter(&String.starts_with?(&1, "user "))

      names = Enum.map(lines, fn line ->
        line |> String.split(" ") |> Enum.at(1)
      end)

      assert names == Enum.sort(names)
    end

    test "password hashes use # prefix in file", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", ">mypass"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      # Should contain #<base64hash>, not >mypass
      refute contents =~ ">mypass"
      assert contents =~ ~r/user alice on #[A-Za-z0-9+\/=]+/
    end

    test "nopass users show nopass in file", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "nopass"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      assert contents =~ "user alice on nopass"
    end

    test "denied commands are serialized as -command", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "-flushdb", "-debug"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      assert contents =~ "-debug"
      assert contents =~ "-flushdb"
      assert contents =~ "+@all"
    end

    test "key patterns with access modes are preserved", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "~cache:*"])
      assert :ok = Acl.set_user("bob", ["on", "%R~readonly:*"])
      assert :ok = Acl.set_user("carol", ["on", "%W~logs:*"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      assert contents =~ "~cache:*"
      assert contents =~ "%R~readonly:*"
      assert contents =~ "%W~logs:*"
    end

    test "creates parent directory if needed", %{tmp_dir: dir} do
      nested = Path.join(dir, "nested/deep")
      assert :ok = Acl.save(nested)
      assert File.exists?(Acl.acl_file_path(nested))
    end

    test "atomic write: no partial files on success", %{tmp_dir: dir} do
      assert :ok = Acl.save(dir)

      # No .tmp files should remain
      files = File.ls!(dir)
      refute Enum.any?(files, &String.contains?(&1, ".tmp"))
    end
  end

  # ---------------------------------------------------------------------------
  # ACL SAVE -- overwrite
  # ---------------------------------------------------------------------------

  describe "save/1 overwrite" do
    test "overwrites existing file", %{tmp_dir: dir} do
      assert :ok = Acl.save(dir)
      assert :ok = Acl.set_user("alice", ["on"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      assert contents =~ "user alice"
    end
  end

  # ---------------------------------------------------------------------------
  # ACL LOAD -- basic functionality
  # ---------------------------------------------------------------------------

  describe "load/1 basic" do
    test "loads users from saved file", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", ">s3cret", "~cache:*", "-@all", "+get"])
      assert :ok = Acl.save(dir)

      # Reset to default only
      Acl.reset!()
      assert Acl.get_user("alice") == nil

      # Load from file
      assert :ok = Acl.load(dir)
      user = Acl.get_user("alice")
      assert user != nil
      assert user.enabled == true
      assert key_globs(user.keys) == ["cache:*"]
      assert MapSet.member?(user.commands, "GET")
    end

    test "load replaces all existing users", %{tmp_dir: dir} do
      # Save with alice
      assert :ok = Acl.set_user("alice", ["on"])
      assert :ok = Acl.save(dir)

      # Add bob (not in file)
      assert :ok = Acl.set_user("bob", ["on"])
      assert Acl.get_user("bob") != nil

      # Load should remove bob
      assert :ok = Acl.load(dir)
      assert Acl.get_user("bob") == nil
      assert Acl.get_user("alice") != nil
    end

    test "returns error for missing file", %{tmp_dir: dir} do
      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "no ACL file"
    end
  end

  # ---------------------------------------------------------------------------
  # Round-trip: SAVE -> reset -> LOAD -> verify
  # ---------------------------------------------------------------------------

  describe "round-trip save/load" do
    test "preserves default user across save/load", %{tmp_dir: dir} do
      assert :ok = Acl.save(dir)
      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("default")
      assert user.enabled == true
      assert user.password == nil
      assert user.commands == :all
      assert user.keys == :all
    end

    test "preserves password hash across save/load", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", ">s3cret"])
      original_hash = Acl.get_user("alice").password
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      loaded_hash = Acl.get_user("alice").password
      assert loaded_hash == original_hash
      # Authentication should still work
      assert {:ok, "alice"} = Acl.authenticate("alice", "s3cret")
    end

    test "preserves enabled/disabled state", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on"])
      assert :ok = Acl.set_user("bob", ["off"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      assert Acl.get_user("alice").enabled == true
      assert Acl.get_user("bob").enabled == false
    end

    test "preserves command permissions", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("reader", ["on", "-@all", "+get", "+mget"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("reader")
      assert MapSet.member?(user.commands, "GET")
      assert MapSet.member?(user.commands, "MGET")
      refute MapSet.member?(user.commands, "SET")
    end

    test "preserves denied commands (denied_commands MapSet)", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "-flushdb", "-debug"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      assert user.commands == :all
      assert MapSet.member?(user.denied_commands, "FLUSHDB")
      assert MapSet.member?(user.denied_commands, "DEBUG")
      # Verify the denial actually works
      assert {:error, _} = Acl.check_command("alice", "FLUSHDB")
      assert :ok = Acl.check_command("alice", "GET")
    end

    test "preserves key patterns with access modes", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "~cache:*"])
      assert :ok = Acl.set_user("bob", ["on", "%R~readonly:*"])
      assert :ok = Acl.set_user("carol", ["on", "%W~logs:*"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      alice = Acl.get_user("alice")
      assert [{_, :rw, _}] = alice.keys

      bob = Acl.get_user("bob")
      assert [{_, :read, _}] = bob.keys

      carol = Acl.get_user("carol")
      assert [{_, :write, _}] = carol.keys
    end

    test "preserves multiple key patterns", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "~cache:*", "~session:*"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      assert key_globs(user.keys) == ["cache:*", "session:*"]
    end

    test "preserves nopass users", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "nopass"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      assert user.password == nil
      assert {:ok, "alice"} = Acl.authenticate("alice", "anything")
    end

    test "preserves allkeys users", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "allkeys"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      assert user.keys == :all
    end

    test "round-trip with many users", %{tmp_dir: dir} do
      # Create 100 users
      for i <- 1..100 do
        assert :ok = Acl.set_user("user_#{i}", ["on", ">pass#{i}", "~prefix#{i}:*"])
      end

      assert :ok = Acl.save(dir)
      Acl.reset!()
      assert :ok = Acl.load(dir)

      # Verify all users exist and authenticate
      for i <- 1..100 do
        user = Acl.get_user("user_#{i}")
        assert user != nil, "user_#{i} should exist after load"
        assert user.enabled == true
        assert {:ok, _} = Acl.authenticate("user_#{i}", "pass#{i}")
      end

      # Default should also exist
      assert Acl.get_user("default") != nil
    end
  end

  # ---------------------------------------------------------------------------
  # ACL LOAD -- validation and error handling
  # ---------------------------------------------------------------------------

  describe "load/1 validation" do
    test "rejects file without default user", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user alice on nopass ~* &* +@all\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "default"

      # Original state should be preserved
      assert Acl.get_user("default") != nil
    end

    test "rejects file with plaintext password", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@all\nuser alice on >s3cret ~* &* +@all\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "plaintext"

      # Original state preserved
      assert Acl.get_user("alice") == nil
    end

    test "rejects file with invalid line (all-or-nothing)", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)

      File.write!(path, """
      user default on nopass ~* &* +@all
      user alice on nopass ~* &* +@all
      this is garbage
      user bob on nopass ~* &* +@all
      """)

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "Invalid ACL line 3"

      # Neither alice nor bob should be loaded (all-or-nothing)
      assert Acl.get_user("alice") == nil
      assert Acl.get_user("bob") == nil
    end

    test "rejects file with invalid password hash encoding", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@all\nuser alice on #not-valid-base64!!! ~* &* +@all\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "invalid password hash"
    end

    test "rejects file with invalid password hash length", %{tmp_dir: dir} do
      # Valid base64 but wrong length (not 48 bytes decoded)
      short_hash = Base.encode64("tooshort")
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@all\nuser alice on ##{short_hash} ~* &* +@all\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "invalid password hash length"
    end

    test "rejects unknown command category", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@nonexistent\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "unknown command category"
    end

    test "rejects unknown token", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@all unknownflag\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "unknown token"
    end

    test "preserves existing state on load failure", %{tmp_dir: dir} do
      # Setup: create alice in memory
      assert :ok = Acl.set_user("alice", ["on", ">pass"])

      # Write invalid file
      path = Acl.acl_file_path(dir)
      File.write!(path, "garbage content\n")

      # Load should fail
      assert {:error, _} = Acl.load(dir)

      # alice should still exist
      assert Acl.get_user("alice") != nil
      assert {:ok, "alice"} = Acl.authenticate("alice", "pass")
    end
  end

  # ---------------------------------------------------------------------------
  # Edge cases -- file format
  # ---------------------------------------------------------------------------

  describe "file format edge cases" do
    test "handles BOM (byte order mark)", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      bom = <<0xEF, 0xBB, 0xBF>>
      File.write!(path, bom <> "user default on nopass ~* &* +@all\n")

      assert :ok = Acl.load(dir)
      assert Acl.get_user("default") != nil
    end

    test "handles Windows line endings (CRLF)", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@all\r\nuser alice on nopass ~* &* +@all\r\n")

      assert :ok = Acl.load(dir)
      assert Acl.get_user("alice") != nil
    end

    test "handles trailing whitespace", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@all   \nuser alice on nopass ~* &* +@all  \n")

      assert :ok = Acl.load(dir)
      assert Acl.get_user("alice") != nil
    end

    test "handles comment lines", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)

      File.write!(path, """
      # This is a comment
      # Another comment
      user default on nopass ~* &* +@all
      # Inline comment between users
      user alice on nopass ~* &* +@all
      """)

      assert :ok = Acl.load(dir)
      assert Acl.get_user("alice") != nil
    end

    test "handles empty lines", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)

      File.write!(path, """
      user default on nopass ~* &* +@all

      user alice on nopass ~* &* +@all


      """)

      assert :ok = Acl.load(dir)
      assert Acl.get_user("alice") != nil
    end

    test "duplicate user definitions: last wins", %{tmp_dir: dir} do
      # Create a valid hash for both definitions
      assert :ok = Acl.set_user("alice", ["on", ">firstpass"])
      first_hash = Acl.get_user("alice").password
      assert :ok = Acl.set_user("alice", [">secondpass"])
      second_hash = Acl.get_user("alice").password

      path = Acl.acl_file_path(dir)

      File.write!(path, """
      user default on nopass ~* &* +@all
      user alice on ##{first_hash} ~cache:* &* +get
      user alice off ##{second_hash} ~session:* &* +set
      """)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      # Last definition should win
      assert user.enabled == false
      assert user.password == second_hash
    end

    test "handles multiple whitespace between tokens", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user  default   on   nopass   ~*   &*   +@all\n")

      assert :ok = Acl.load(dir)
      assert Acl.get_user("default") != nil
    end
  end

  # ---------------------------------------------------------------------------
  # Edge cases -- security
  # ---------------------------------------------------------------------------

  describe "security edge cases" do
    test "path traversal is rejected" do
      # Acl.save(data_dir) always writes to data_dir/acl.conf, so the
      # data_dir parameter itself cannot cause path traversal.
      # The real protection is that data_dir comes from application config,
      # not from client input. Verify save works with a valid dir
      # and doesn't crash with a nonexistent dir.
      result = Acl.save("/nonexistent/path/that/doesnt/exist")
      assert result == :ok or match?({:error, _}, result)
    end

    test "symlink ACL file is rejected", %{tmp_dir: dir} do
      # Create a symlink at the ACL file path
      real_file = Path.join(dir, "real_acl.conf")
      File.write!(real_file, "user default on nopass ~* &* +@all\n")

      acl_path = Acl.acl_file_path(dir)
      File.ln_s!(real_file, acl_path)

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "symlink"
    end

    test "never stores plaintext passwords in file", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", ">MySecretPass123!"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      refute contents =~ "MySecretPass123!"
      refute contents =~ ">MySecretPass123!"
    end

    test "file with extremely long line is rejected", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      long_line = "user default on nopass ~* &* +@all" <> String.duplicate("x", 2_000_000)
      File.write!(path, long_line <> "\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "maximum length"
    end
  end

  # ---------------------------------------------------------------------------
  # Permission enforcement after LOAD
  # ---------------------------------------------------------------------------

  describe "permission enforcement after load" do
    test "loaded user permissions are enforced", %{tmp_dir: dir} do
      # Create user with restricted permissions
      assert :ok = Acl.set_user("reader", ["on", ">pass", "-@all", "+get", "+mget"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      # Check command enforcement
      assert :ok = Acl.check_command("reader", "GET")
      assert :ok = Acl.check_command("reader", "MGET")
      assert {:error, _} = Acl.check_command("reader", "SET")
      assert {:error, _} = Acl.check_command("reader", "DEL")
    end

    test "loaded denied commands are enforced", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", ">pass", "-flushdb"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      assert :ok = Acl.check_command("alice", "GET")
      assert {:error, _} = Acl.check_command("alice", "FLUSHDB")
    end

    test "loaded key patterns are enforced", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", ">pass", "~cache:*"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      assert :ok = Acl.check_key_access("alice", "cache:foo", :read)
      assert {:error, _} = Acl.check_key_access("alice", "other:foo", :read)
    end

    test "disabled user remains disabled after load", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["off", ">pass"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      assert {:error, _} = Acl.authenticate("alice", "pass")
    end
  end

  # ---------------------------------------------------------------------------
  # Auto-save (debounced)
  # ---------------------------------------------------------------------------

  describe "auto-save" do
    test "auto-save writes file after SETUSER when enabled", %{tmp_dir: dir} do
      # Enable auto-save and point data_dir to our temp dir
      prev_auto = Application.get_env(:ferricstore, :acl_auto_save)
      prev_dir = Application.get_env(:ferricstore, :data_dir)
      Application.put_env(:ferricstore, :acl_auto_save, true)
      Application.put_env(:ferricstore, :data_dir, dir)

      on_exit(fn ->
        if prev_auto, do: Application.put_env(:ferricstore, :acl_auto_save, prev_auto), else: Application.delete_env(:ferricstore, :acl_auto_save)
        if prev_dir, do: Application.put_env(:ferricstore, :data_dir, prev_dir)
      end)

      assert :ok = Acl.set_user("alice", ["on"])

      # Wait for debounce timer (1 second + buffer)
      Process.sleep(1_500)

      path = Acl.acl_file_path(dir)
      assert File.exists?(path)
      contents = File.read!(path)
      assert contents =~ "user alice"
    end

    test "auto-save debounces rapid mutations", %{tmp_dir: dir} do
      prev_auto = Application.get_env(:ferricstore, :acl_auto_save)
      prev_dir = Application.get_env(:ferricstore, :data_dir)
      Application.put_env(:ferricstore, :acl_auto_save, true)
      Application.put_env(:ferricstore, :data_dir, dir)

      on_exit(fn ->
        if prev_auto, do: Application.put_env(:ferricstore, :acl_auto_save, prev_auto), else: Application.delete_env(:ferricstore, :acl_auto_save)
        if prev_dir, do: Application.put_env(:ferricstore, :data_dir, prev_dir)
      end)

      # Rapid fire mutations
      for i <- 1..10 do
        Acl.set_user("user_#{i}", ["on"])
      end

      # Wait for debounce
      Process.sleep(1_500)

      path = Acl.acl_file_path(dir)
      assert File.exists?(path)
      contents = File.read!(path)
      # All 10 users should be in the file (saved after debounce)
      for i <- 1..10 do
        assert contents =~ "user_#{i}"
      end
    end

    test "auto-save does not fire when disabled", %{tmp_dir: dir} do
      prev_auto = Application.get_env(:ferricstore, :acl_auto_save)
      prev_dir = Application.get_env(:ferricstore, :data_dir)
      Application.put_env(:ferricstore, :acl_auto_save, false)
      Application.put_env(:ferricstore, :data_dir, dir)

      on_exit(fn ->
        if prev_auto, do: Application.put_env(:ferricstore, :acl_auto_save, prev_auto), else: Application.delete_env(:ferricstore, :acl_auto_save)
        if prev_dir, do: Application.put_env(:ferricstore, :data_dir, prev_dir)
      end)

      assert :ok = Acl.set_user("alice", ["on"])
      Process.sleep(1_500)

      refute File.exists?(Acl.acl_file_path(dir))
    end
  end

  # ---------------------------------------------------------------------------
  # Concurrent SAVE/LOAD
  # ---------------------------------------------------------------------------

  describe "concurrent operations" do
    test "concurrent saves don't corrupt the file", %{tmp_dir: dir} do
      # Create some users
      for i <- 1..20 do
        Acl.set_user("user_#{i}", ["on"])
      end

      # Launch 10 concurrent saves
      tasks =
        for _ <- 1..10 do
          Task.async(fn -> Acl.save(dir) end)
        end

      results = Enum.map(tasks, &Task.await/1)
      assert Enum.all?(results, &(&1 == :ok))

      # File should be valid and loadable
      Acl.reset!()
      assert :ok = Acl.load(dir)

      # All users should exist
      for i <- 1..20 do
        assert Acl.get_user("user_#{i}") != nil
      end
    end

    test "concurrent save and load don't deadlock", %{tmp_dir: dir} do
      # Save initial state
      assert :ok = Acl.set_user("alice", ["on"])
      assert :ok = Acl.save(dir)

      # Launch concurrent save and load
      tasks =
        for _ <- 1..5 do
          [
            Task.async(fn -> Acl.save(dir) end),
            Task.async(fn -> Acl.load(dir) end)
          ]
        end
        |> List.flatten()

      results = Enum.map(tasks, &Task.await(&1, 10_000))
      # All should complete without timeout
      assert length(results) == 10
    end
  end

  # ---------------------------------------------------------------------------
  # File corruption recovery
  # ---------------------------------------------------------------------------

  describe "corruption recovery" do
    test "completely empty file is handled", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "default"
    end

    test "file with only comments is handled", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "# just a comment\n# another comment\n")

      assert {:error, msg} = Acl.load(dir)
      assert msg =~ "default"
    end

    test "binary garbage is rejected", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, :crypto.strong_rand_bytes(1024))

      assert {:error, _} = Acl.load(dir)
    end

    test "truncated file (missing newline) is handled", %{tmp_dir: dir} do
      path = Acl.acl_file_path(dir)
      File.write!(path, "user default on nopass ~* &* +@all")

      # Should work -- no trailing newline is fine
      assert :ok = Acl.load(dir)
      assert Acl.get_user("default") != nil
    end
  end

  # ---------------------------------------------------------------------------
  # Large scale
  # ---------------------------------------------------------------------------

  describe "large scale" do
    test "saves and loads 1000 users", %{tmp_dir: dir} do
      for i <- 1..1000 do
        Acl.set_user("user_#{String.pad_leading(to_string(i), 4, "0")}", ["on", ">pass#{i}"])
      end

      assert :ok = Acl.save(dir)

      # Check file size is reasonable
      {:ok, stat} = File.stat(Acl.acl_file_path(dir))
      assert stat.size > 0
      assert stat.size < 50_000_000

      Acl.reset!()
      assert :ok = Acl.load(dir)

      # Verify count
      users = Acl.list_users()
      assert length(users) == 1001  # 1000 + default

      # Spot check authentication
      assert {:ok, _} = Acl.authenticate("user_0001", "pass1")
      assert {:ok, _} = Acl.authenticate("user_0500", "pass500")
      assert {:ok, _} = Acl.authenticate("user_1000", "pass1000")
    end
  end

  # ---------------------------------------------------------------------------
  # acl_file_path/1
  # ---------------------------------------------------------------------------

  describe "acl_file_path/1" do
    test "returns correct path" do
      assert Acl.acl_file_path("/data") == "/data/acl.conf"
      assert Acl.acl_file_path("/tmp/test") == "/tmp/test/acl.conf"
    end
  end

  # ---------------------------------------------------------------------------
  # Read-only filesystem handling
  # ---------------------------------------------------------------------------

  describe "read-only filesystem" do
    test "save returns error on permission denied", %{tmp_dir: dir} do
      # Make directory read-only
      File.chmod!(dir, 0o444)

      result = Acl.save(dir)
      assert {:error, msg} = result
      assert msg =~ "ACL save failed"

      # Restore permissions for cleanup
      File.chmod!(dir, 0o755)
    end
  end

  # ---------------------------------------------------------------------------
  # File format: command serialization
  # ---------------------------------------------------------------------------

  describe "command serialization" do
    test "explicit command list round-trips correctly", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "-@all", "+get", "+set", "+del"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      assert MapSet.member?(user.commands, "GET")
      assert MapSet.member?(user.commands, "SET")
      assert MapSet.member?(user.commands, "DEL")
      assert MapSet.size(user.commands) == 3
    end

    test "allcommands round-trips correctly", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "allcommands"])
      assert :ok = Acl.save(dir)

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      assert user.commands == :all
    end

    test "nocommands user round-trips (empty command set)", %{tmp_dir: dir} do
      assert :ok = Acl.set_user("alice", ["on", "-@all"])
      assert :ok = Acl.save(dir)

      contents = File.read!(Acl.acl_file_path(dir))
      # User with no commands should not have +@all in the file
      alice_line = contents |> String.split("\n") |> Enum.find(&String.contains?(&1, "user alice"))
      refute alice_line =~ "+@all"

      Acl.reset!()
      assert :ok = Acl.load(dir)

      user = Acl.get_user("alice")
      assert user.commands == MapSet.new()
    end
  end
end
