defmodule FerricstoreEcto.Cache do
  @moduledoc """
  Core cache logic for the FerricStore Ecto L2 cache.

  Provides entity-level caching (get/put/invalidate) and query-level
  caching (all/one) with generation-counter-based invalidation.

  This module is called by the overridden Repo functions generated by
  `FerricStore.Ecto.CachedRepo`. It should not be called directly
  by application code.

  ## Entity Cache

  Entities are stored as FerricStore hashes keyed by
  `"ecto:{source}:{pk}"`. Each schema field is stored as an individual
  hash field using `FerricstoreEcto.FieldCodec` for type-aware
  serialization. On read, all fields are fetched via `HGETALL` and
  deserialized back to the original Ecto types.

  Primary key fields are excluded from the hash because they are encoded
  in the cache key itself. Associations are not stored -- only the
  schema's own fields (including foreign key fields like `user_id`).

  ### Entity Cache Keys

      "ecto:users:42"          # single PK
      "ecto:user_roles:1:3"    # composite PK (user_id=1, role_id=3)

  ## Query Cache

  Query results are stored as PK lists, not full entities. This means
  the entity cache is the single source of truth for entity data, and
  query cache entries are lightweight.

  - **Ordered queries** (with ORDER BY): PKs stored as a FerricStore LIST
    via `RPUSH`, preserving order
  - **Unordered queries** (without ORDER BY): PKs stored as a FerricStore
    SET via `SADD`
  - **Empty results**: A sentinel string `"__empty__"` is stored to
    distinguish "query returned zero rows" from "query not cached"

  ### Query Cache Keys

  Query cache keys embed the table's generation counter:

      "ecto:q:{query_hash}:g{generation}:pks"

  Example:

      "ecto:q:1234567:g0:pks"   # query hash 1234567, generation 0
      "ecto:q:1234567:g1:pks"   # same query, generation 1 (after mutation)

  ### Generation Counter Invalidation

  Each table has a generation counter at `"ecto:gen:{source}"`:

      "ecto:gen:users"   # current generation for the users table

  When a mutation occurs, the counter is incremented via `INCR`. This
  makes all existing query cache entries for that table unreachable
  (since they reference the old generation number) without needing to
  find and delete them. Old entries expire naturally via TTL.

  ### Double-Check Protocol

  To prevent stale reads during concurrent mutations, the query cache
  read uses a double-check protocol:

  1. Read generation counter (gen1)
  2. Read PK list using gen1 in the cache key
  3. Re-read generation counter (gen2)
  4. If gen1 != gen2, a mutation happened during our read -- discard
     and fall through to DB

  ## Query Resolution

  When a query cache hit returns a list of PKs, each PK is resolved
  through the entity cache:

  1. For each PK, attempt `HGETALL ecto:{table}:{pk}`
  2. If all PKs are found in entity cache: return reconstructed structs
  3. If any PK is missing (partial miss): fall back to DB for the
     entire query, then repopulate both caches

  ## Invalidation Summary

  | Mutation | Entity Cache | Query Cache |
  |----------|-------------|-------------|
  | `insert` | `DEL ecto:{table}:{pk}` | `INCR ecto:gen:{table}` |
  | `update` | `DEL ecto:{table}:{pk}` | `INCR ecto:gen:{table}` |
  | `delete` | `DEL ecto:{table}:{pk}` | `INCR ecto:gen:{table}` |
  | `insert_all` | (none) | `INCR ecto:gen:{table}` |
  | `update_all` | `DEL` all entries for table | `INCR ecto:gen:{table}` |
  | `delete_all` | `DEL` all entries for table | `INCR ecto:gen:{table}` |

  ## Cache Modes

  The cache mode is extracted from the `:cache` option in query opts:

  | Value | Mode | Reads Cache? | Populates Cache? |
  |-------|------|:---:|:---:|
  | `true` (default) | `:normal` | Yes | Yes |
  | `false` | `:ignore` | No | No |
  | `:refresh` | `:refresh` | No | Yes |
  | `:cache_only` | `:cache_only` | Yes | No DB fallback |
  | `:put_only` | `:put_only` | No | Yes |
  | `[ttl: ms]` | `:normal` | Yes | Yes (custom TTL) |
  """

  alias FerricstoreEcto.FieldCodec
  alias FerricstoreEcto.QueryHash

  require Logger

  # ---------------------------------------------------------------------------
  # Types
  # ---------------------------------------------------------------------------

  @type cache_mode :: :normal | :ignore | :refresh | :cache_only | :put_only
  @type cache_opts :: keyword()

  # ---------------------------------------------------------------------------
  # Entity cache: read
  # ---------------------------------------------------------------------------

  @doc """
  Attempts to read an entity from the L2 cache.

  Returns `{:hit, struct}` on cache hit, or `:miss` on cache miss.
  Respects the cache mode extracted from opts.
  """
  @spec cached_get(module(), module(), term(), keyword()) :: {:hit, Ecto.Schema.t() | nil} | :miss
  def cached_get(_repo, schema, id, opts) do
    mode = cache_mode(opts)

    cond do
      not cacheable?(schema) ->
        :miss

      mode == :ignore ->
        :miss

      mode in [:refresh, :put_only] ->
        :miss

      true ->
        source = schema.__schema__(:source)
        cache_key = entity_key(source, id)
        l2_get(cache_key, schema)
    end
  end

  @doc """
  Populates the entity cache after a DB read.

  Only called when the entity is cacheable and not nil.
  """
  @spec populate_entity(module(), Ecto.Schema.t() | nil, keyword()) :: :ok
  def populate_entity(_schema, nil, _opts), do: :ok

  def populate_entity(schema, struct, opts) do
    mode = cache_mode(opts)

    if cacheable?(schema) and mode != :ignore do
      source = schema.__schema__(:source)
      pk = primary_key_value(schema, struct)
      cache_key = entity_key(source, pk)
      ttl = resolve_ttl(schema, opts)
      l2_put(cache_key, struct, ttl)
    end

    :ok
  end

  # ---------------------------------------------------------------------------
  # Entity cache: invalidate
  # ---------------------------------------------------------------------------

  @doc """
  Invalidates the entity cache entry for the given struct and bumps
  the query generation counter for the struct's source table.
  """
  @spec invalidate_entity(Ecto.Schema.t()) :: :ok
  def invalidate_entity(struct) do
    schema = struct.__struct__

    if cacheable?(schema) do
      source = schema.__schema__(:source)
      pk = primary_key_value(schema, struct)
      cache_key = entity_key(source, pk)

      FerricStore.del(cache_key)
      invalidate_query_caches(source)
    end

    :ok
  end

  @doc """
  Invalidates all query caches for a table by incrementing the
  generation counter. Called on insert/update/delete.
  """
  @spec invalidate_query_caches(String.t()) :: :ok
  def invalidate_query_caches(source) do
    FerricStore.incr("ecto:gen:#{source}")
    :ok
  end

  # ---------------------------------------------------------------------------
  # Query cache: read
  # ---------------------------------------------------------------------------

  @doc """
  Attempts to read query results from the L2 query cache.

  On hit, returns `{:hit, pks}` where `pks` is a list of primary key
  strings. The caller resolves each PK through the entity cache.

  Uses generation-counter double-check to prevent stale reads:
  reads gen before lookup, rechecks after, discards if changed.
  """
  @spec cached_all(module(), Ecto.Query.t(), keyword()) ::
          {:hit, [String.t()]} | :miss
  def cached_all(_repo, query, opts) do
    mode = cache_mode(opts)
    schema = QueryHash.primary_schema(query)

    cond do
      is_nil(schema) ->
        :miss

      not cacheable?(schema) ->
        :miss

      mode == :ignore ->
        :miss

      mode in [:refresh, :put_only] ->
        :miss

      not cacheable_query?(query) ->
        :miss

      true ->
        source = schema.__schema__(:source)
        q_hash = QueryHash.hash(query)

        # Read generation counter BEFORE cache lookup
        {:ok, gen1} = FerricStore.get("ecto:gen:#{source}")
        gen1 = gen1 || "0"

        pk_key = query_pk_key(q_hash, gen1)

        case read_pk_list(pk_key, query) do
          {:ok, pks} ->
            # Recheck generation to prevent stale reads
            {:ok, gen2} = FerricStore.get("ecto:gen:#{source}")
            gen2 = gen2 || "0"

            if gen1 == gen2 do
              {:hit, pks}
            else
              # A write happened during our read -- discard
              :miss
            end

          :empty ->
            :miss
        end
    end
  end

  @doc """
  Populates the query cache with PK list after a DB query.

  Also populates entity cache for each result row.
  """
  @spec populate_query(module(), Ecto.Query.t(), [Ecto.Schema.t()], keyword()) :: :ok
  def populate_query(_repo, query, results, opts) do
    mode = cache_mode(opts)
    schema = QueryHash.primary_schema(query)

    if not is_nil(schema) and cacheable?(schema) and mode != :ignore and cacheable_query?(query) do
      source = schema.__schema__(:source)
      ttl = resolve_ttl(schema, opts)
      q_hash = QueryHash.hash(query)

      # Read current generation for cache key
      {:ok, gen} = FerricStore.get("ecto:gen:#{source}")
      gen = gen || "0"
      pk_key = query_pk_key(q_hash, gen)

      pks = Enum.map(results, fn r -> to_string(primary_key_value(schema, r)) end)

      if length(pks) > 0 do
        if QueryHash.has_order_by?(query) do
          FerricStore.rpush(pk_key, pks)
        else
          FerricStore.sadd(pk_key, pks)
        end

        if ttl > 0, do: FerricStore.expire(pk_key, ttl)
      else
        # Store empty marker so we don't re-query
        FerricStore.set(pk_key, "__empty__", ttl: ttl)
      end

      # Populate entity cache for each result
      Enum.each(results, fn struct ->
        pk = primary_key_value(schema, struct)
        l2_put(entity_key(source, pk), struct, ttl)
      end)
    end

    :ok
  end

  @doc """
  Resolves a list of PK strings through the entity cache.

  For each PK, attempts an entity cache hit. On miss, returns `:miss`
  for the caller to fall back to DB.
  """
  @spec resolve_pks(module(), module(), [String.t()], keyword()) ::
          {:ok, [Ecto.Schema.t()]} | :partial_miss
  def resolve_pks(_repo, schema, pks, _opts) do
    source = schema.__schema__(:source)

    results =
      Enum.map(pks, fn pk_str ->
        cache_key = entity_key(source, pk_str)

        case l2_get(cache_key, schema) do
          {:hit, struct} ->
            struct

          :miss ->
            # Entity not in cache -- need DB fetch
            :miss
        end
      end)

    if Enum.any?(results, &(&1 == :miss)) do
      :partial_miss
    else
      {:ok, results}
    end
  end

  # ---------------------------------------------------------------------------
  # Helpers: cacheable checks
  # ---------------------------------------------------------------------------

  @doc """
  Returns `true` if the given schema module has opted in to caching
  via `use FerricStore.Ecto.Cacheable` and caching is enabled.
  """
  @spec cacheable?(module()) :: boolean()
  def cacheable?(schema) when is_atom(schema) do
    function_exported?(schema, :__ferricstore_cache_config__, 0) and
      schema.__ferricstore_cache_config__().enabled
  end

  @doc """
  Returns `true` if the query is eligible for caching.

  Queries with locks, subqueries in FROM, or CTEs are not cached.
  """
  @spec cacheable_query?(Ecto.Query.t()) :: boolean()
  def cacheable_query?(%Ecto.Query{lock: lock}) when not is_nil(lock), do: false
  def cacheable_query?(%Ecto.Query{combinations: [_ | _]}), do: false

  def cacheable_query?(%Ecto.Query{from: %Ecto.Query.FromExpr{source: {table, _}}})
      when is_binary(table) do
    true
  end

  def cacheable_query?(_query), do: false

  # ---------------------------------------------------------------------------
  # Helpers: cache mode
  # ---------------------------------------------------------------------------

  @doc """
  Extracts the cache mode from query options.
  """
  @spec cache_mode(keyword()) :: cache_mode()
  def cache_mode(opts) do
    case Keyword.get(opts, :cache, true) do
      true -> :normal
      false -> :ignore
      :refresh -> :refresh
      :cache_only -> :cache_only
      :put_only -> :put_only
      [_ | _] -> :normal
      _ -> :normal
    end
  end

  @doc """
  Strips the `:cache` option from the opts list before passing to
  the underlying Ecto Repo function.
  """
  @spec strip_cache_opts(keyword()) :: keyword()
  def strip_cache_opts(opts) do
    Keyword.delete(opts, :cache)
  end

  # ---------------------------------------------------------------------------
  # Helpers: cache keys
  # ---------------------------------------------------------------------------

  @doc """
  Builds the entity cache key for the given source table and primary key.
  """
  @spec entity_key(String.t(), term()) :: String.t()
  def entity_key(source, pk) do
    "ecto:#{source}:#{pk}"
  end

  # ---------------------------------------------------------------------------
  # Private: L2 entity operations
  # ---------------------------------------------------------------------------

  defp l2_get(cache_key, schema) do
    case FerricStore.hgetall(cache_key) do
      {:ok, %{} = fields} when map_size(fields) > 0 ->
        pk_values = extract_pk_from_cache_key(cache_key, schema)
        deserialized = FieldCodec.deserialize_fields(schema, fields)
        merged = Map.merge(deserialized, pk_values)
        struct = struct(schema, merged)

        # Restore the __meta__ to :loaded state
        struct = Ecto.put_meta(struct, state: :loaded)
        {:hit, struct}

      _ ->
        :miss
    end
  end

  defp l2_put(cache_key, struct, ttl) do
    fields = FieldCodec.serialize_fields(struct)
    FerricStore.hset(cache_key, fields)
    if ttl > 0, do: FerricStore.expire(cache_key, ttl)
    :ok
  end

  defp extract_pk_from_cache_key(cache_key, schema) do
    # Key format: "ecto:{source}:{pk}"
    pk_fields = schema.__schema__(:primary_key)

    case pk_fields do
      [single_pk] ->
        # "ecto:users:42" -> "42"
        source = schema.__schema__(:source)
        prefix = "ecto:#{source}:"
        pk_str = String.replace_prefix(cache_key, prefix, "")
        pk_type = schema.__schema__(:type, single_pk)
        %{single_pk => FieldCodec.decode(pk_type, pk_str)}

      _composite ->
        # Composite PKs: "ecto:table:pk1:pk2" -- split by ":"
        source = schema.__schema__(:source)
        prefix = "ecto:#{source}:"
        pk_str = String.replace_prefix(cache_key, prefix, "")
        pk_parts = String.split(pk_str, ":")

        Enum.zip(pk_fields, pk_parts)
        |> Map.new(fn {field, val_str} ->
          pk_type = schema.__schema__(:type, field)
          {field, FieldCodec.decode(pk_type, val_str)}
        end)
    end
  end

  # ---------------------------------------------------------------------------
  # Private: query cache operations
  # ---------------------------------------------------------------------------

  defp query_pk_key(q_hash, gen) do
    "ecto:q:#{q_hash}:g#{gen}:pks"
  end

  defp read_pk_list(pk_key, query) do
    # Try LIST first (ordered queries), then SET, then plain string marker
    if QueryHash.has_order_by?(query) do
      case FerricStore.lrange(pk_key, 0, -1) do
        {:ok, pks} when is_list(pks) and length(pks) > 0 -> {:ok, pks}
        _ -> check_empty_marker(pk_key)
      end
    else
      case FerricStore.smembers(pk_key) do
        {:ok, members} when is_list(members) and length(members) > 0 -> {:ok, members}
        _ -> check_empty_marker(pk_key)
      end
    end
  end

  defp check_empty_marker(pk_key) do
    case FerricStore.get(pk_key) do
      {:ok, "__empty__"} -> {:ok, []}
      _ -> :empty
    end
  end

  # ---------------------------------------------------------------------------
  # Private: TTL resolution
  # ---------------------------------------------------------------------------

  defp resolve_ttl(schema, opts) do
    # Check for per-query TTL override
    case Keyword.get(opts, :cache) do
      opts_list when is_list(opts_list) ->
        Keyword.get(opts_list, :ttl, default_ttl(schema))

      _ ->
        default_ttl(schema)
    end
  end

  defp default_ttl(schema) do
    if function_exported?(schema, :__ferricstore_cache_config__, 0) do
      schema.__ferricstore_cache_config__().ttl
    else
      :timer.minutes(5)
    end
  end

  # ---------------------------------------------------------------------------
  # Private: primary key extraction
  # ---------------------------------------------------------------------------

  @doc false
  def primary_key_value(schema, struct) do
    pk_fields = schema.__schema__(:primary_key)

    case pk_fields do
      [single_pk] ->
        Map.get(struct, single_pk)

      multi ->
        multi
        |> Enum.map(&Map.get(struct, &1))
        |> Enum.join(":")
    end
  end
end
