defmodule Ferricstore.Bitcask.NIF do
  @moduledoc false
  use Rustler, otp_app: :ferricstore, crate: "ferricstore_bitcask", skip_compilation?: true
  def new(_path), do: :erlang.nif_error(:nif_not_loaded)
  def get(_store, _key), do: :erlang.nif_error(:nif_not_loaded)
  def get_zero_copy(_store, _key), do: :erlang.nif_error(:nif_not_loaded)
  def get_file_ref(_store, _key), do: :erlang.nif_error(:nif_not_loaded)
  def put(_store, _key, _value, _expire_at_ms), do: :erlang.nif_error(:nif_not_loaded)
  def delete(_store, _key), do: :erlang.nif_error(:nif_not_loaded)
  def put_batch(_store, _batch), do: :erlang.nif_error(:nif_not_loaded)
  def put_batch_async(_store, _batch), do: :erlang.nif_error(:nif_not_loaded)
  def keys(_store), do: :erlang.nif_error(:nif_not_loaded)
  def write_hint(_store), do: :erlang.nif_error(:nif_not_loaded)
  def purge_expired(_store), do: :erlang.nif_error(:nif_not_loaded)
  def get_all(_store), do: :erlang.nif_error(:nif_not_loaded)
  def get_batch(_store, _keys), do: :erlang.nif_error(:nif_not_loaded)
  def get_range(_store, _min_key, _max_key, _max_count), do: :erlang.nif_error(:nif_not_loaded)
  def read_modify_write(_store, _key, _operation), do: :erlang.nif_error(:nif_not_loaded)
  def get_all_zero_copy(_store), do: :erlang.nif_error(:nif_not_loaded)
  def get_batch_zero_copy(_store, _keys), do: :erlang.nif_error(:nif_not_loaded)
  def get_range_zero_copy(_store, _min_key, _max_key, _max_count), do: :erlang.nif_error(:nif_not_loaded)
  def shard_stats(_store), do: :erlang.nif_error(:nif_not_loaded)
  def file_sizes(_store), do: :erlang.nif_error(:nif_not_loaded)
  def run_compaction(_store, _file_ids), do: :erlang.nif_error(:nif_not_loaded)
  def available_disk_space(_store), do: :erlang.nif_error(:nif_not_loaded)
  def hnsw_new(_dims, _m, _ef_construction, _metric), do: :erlang.nif_error(:nif_not_loaded)
  def hnsw_add(_index, _key, _vector), do: :erlang.nif_error(:nif_not_loaded)
  def hnsw_delete(_index, _key), do: :erlang.nif_error(:nif_not_loaded)
  def hnsw_search(_index, _query, _k, _ef), do: :erlang.nif_error(:nif_not_loaded)
  def hnsw_count(_index), do: :erlang.nif_error(:nif_not_loaded)
  def vsearch_nif(_index, _query, _k, _ef), do: :erlang.nif_error(:nif_not_loaded)
  def topk_create(_k, _width, _depth, _decay), do: :erlang.nif_error(:nif_not_loaded)
  def topk_add(_topk, _items), do: :erlang.nif_error(:nif_not_loaded)
  def topk_incrby(_topk, _pairs), do: :erlang.nif_error(:nif_not_loaded)
  def topk_query(_topk, _items), do: :erlang.nif_error(:nif_not_loaded)
  def topk_list(_topk), do: :erlang.nif_error(:nif_not_loaded)
  def topk_list_with_count(_topk), do: :erlang.nif_error(:nif_not_loaded)
  def topk_info(_topk), do: :erlang.nif_error(:nif_not_loaded)
  def topk_to_bytes(_topk), do: :erlang.nif_error(:nif_not_loaded)
  def topk_from_bytes(_data), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_create(_a, _b, _c, _d), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_add(_f, _i), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_addnx(_f, _i), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_del(_f, _i), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_exists(_f, _i), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_mexists(_f, _i), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_count(_f, _i), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_info(_f), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_serialize(_f), do: :erlang.nif_error(:nif_not_loaded)
  def cuckoo_deserialize(_d), do: :erlang.nif_error(:nif_not_loaded)

  # -- Tokio async IO NIFs --
  def get_async(_store, _key), do: :erlang.nif_error(:nif_not_loaded)
  def delete_async(_store, _key), do: :erlang.nif_error(:nif_not_loaded)
  def put_batch_tokio_async(_store, _batch), do: :erlang.nif_error(:nif_not_loaded)
  def write_hint_async(_store), do: :erlang.nif_error(:nif_not_loaded)
  def purge_expired_async(_store), do: :erlang.nif_error(:nif_not_loaded)
  def run_compaction_async(_store, _file_ids), do: :erlang.nif_error(:nif_not_loaded)

  # -- Count-Min Sketch NIFs --
  def cms_create(_width, _depth), do: :erlang.nif_error(:nif_not_loaded)
  def cms_incrby(_resource, _items), do: :erlang.nif_error(:nif_not_loaded)
  def cms_query(_resource, _elements), do: :erlang.nif_error(:nif_not_loaded)
  def cms_merge(_dest, _sources), do: :erlang.nif_error(:nif_not_loaded)
  def cms_info(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def cms_to_bytes(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def cms_from_bytes(_data), do: :erlang.nif_error(:nif_not_loaded)

  # -- Bloom filter NIFs --
  def bloom_create(_path, _num_bits, _num_hashes), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_open(_path), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_add(_resource, _element), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_madd(_resource, _elements), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_exists(_resource, _element), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_mexists(_resource, _elements), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_card(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_info(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def bloom_delete(_resource), do: :erlang.nif_error(:nif_not_loaded)

  # -- TDigest NIFs --
  def tdigest_create(_compression), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_add(_resource, _values), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_quantile(_resource, _quantiles), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_cdf(_resource, _values), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_trimmed_mean(_resource, _lo, _hi), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_min(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_max(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_info(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_rank(_resource, _values), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_revrank(_resource, _values), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_byrank(_resource, _ranks), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_byrevrank(_resource, _ranks), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_merge(_resources, _compression), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_reset(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_serialize(_resource), do: :erlang.nif_error(:nif_not_loaded)
  def tdigest_deserialize(_data), do: :erlang.nif_error(:nif_not_loaded)

  # -- Tracking allocator --
  def rust_allocated_bytes, do: :erlang.nif_error(:nif_not_loaded)
end
