%{
  # This file is auto-generated by:
  #   mix rustler_precompiled.download Ferricstore.Bitcask.NIF --all --print
  #
  # After a GitHub Release is created with all platform binaries,
  # run the above command and commit the updated checksums.
}
